---

platform: linux

image_resource:
  type: docker-image
  source: {repository: emeraldsquad/cf-cli}

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PIVNET_API_TOKEN:
  NO_PROXY:
  OM_IP:
  IAAS:

inputs:
  - name: pcf-pipelines

run:
  path: bash
  args: [pcf-pipelines/tasks/upload-product-and-stemcell/test1.sh]
